### ISSUE TITLE
test từng model

### ISSUE THREAD

**Issue by tiamo405** [hungk64it1x/zac-2022#1]
vì lí do máy k đủ ram nên mình muốn test từng model 1. 
`models.append(Model(name = 'convnext_large', checkpoint_model='checkpoints/convnext_large_fold0_224_bs_32_ema/checkpoint-best.pth'\
    , model_prefix='', size= 224))`
cho mình hỏi output ra cho mỗi ảnh thì như nào là real như nào là fake
`output = model.predict(input)
out =  [0.9546301  0.04536991]` 
các số như này thì sẽ so sánh như nào để biết 1 video là real hay fake
cám ơn đã đọc và source code của nhóm bạn

**Comment by hungk64it1x** [comment]
Vì output đề bài yêu cầu là liveness score nên sẽ lấy số ở cột thứ 2 nha bạn vì mình để class fake là 0 và real là 1.
Ví dụ: [0.9546301  0.04536991] sẽ là 0.04536991.

**Comment by tiamo405** [comment]
> Vì output đề bài yêu cầu là liveness score nên sẽ lấy số ở cột thứ 2 nha bạn vì mình để class fake là 0 và real là 1. Ví dụ: [0.9546301 0.04536991] sẽ là 0.04536991.

cám ơn bạn. Một điều nữa là mình có 2 gpu nhưng khi mình train lại model chỉ muốn dùng 1 gpu thì phần utils cần chỉnh sửa như thế nào. nếu 2 gpu khác nhau thì có thể train được nếu giữ nguyên không ?
cám ơn bạn đã giải đáp

**Comment by hungk64it1x** [comment]
Bạn để CUDA_VISIBLE_DEVICES là được bạn ạ. 
Ví dụ: CUDA_VISIBLE_DEVICES=0 python train_convnext_large.sh
Nếu bị lỗi thì bạn sửa distributed là được nha
